version: 2
multi-ecosystem-groups:
  tauri:
    schedule:
      interval: "monthly"
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "cargo"
    directory: "src-tauri/"
    schedule:
      interval: "monthly"
    groups:
      backend-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "tauri*"
    patterns:
      - "tauri*"
      - "tauri-plugin*"
    multi-ecosystem-group: "tauri"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      frontend-deps:
        patterns:
          - "*"
        exclude-patterns:
          - "@tauri*"
    patterns:
      - "@tauri-apps/*"
    multi-ecosystem-group: "tauri"
