// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameConfig = {
  isInstalled: boolean;
  version: string | null;
  texturePacks: Array<string>;
  secondsPlayed: bigint;
  mods: { [key in string]?: { [key in string]?: string } };
};
