// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecompilerSettings } from "./DecompilerSettings";
import type { GameConfig } from "./GameConfig";
import type { Requirements } from "./Requirements";
import type { SupportedGame } from "./SupportedGame";
import type { UISettings } from "./UISettings";

export type LauncherConfig = {
  version: string;
  requirements: Requirements;
  games: { [key in SupportedGame]?: GameConfig };
  installationDir: string | null;
  activeVersion: string | null;
  locale: string;
  modSources: Array<string>;
  decompilerSettings: DecompilerSettings;
  checkForLatestModVersion: boolean;
  proceedAfterSuccessfulOperation: boolean;
  autoUpdateGames: boolean;
  deletePreviousVersions: boolean;
  ui: UISettings;
};
