// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModVersion } from "./ModVersion";

export type ModInfo = {
  displayName: string;
  description: string;
  authors: Array<string>;
  tags: Array<string>;
  supportedGames: Array<string>;
  websiteUrl: string | null;
  coverArtUrl: string | null;
  thumbnailArtUrl: string | null;
  versions: Array<ModVersion>;
};
