// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModInfo } from "./ModInfo";

export type ModSourceData = {
  schemaVersion: string;
  sourceName: string;
  lastUpdated: string;
  mods: { [key in string]?: ModInfo };
  texturePacks: { [key in string]?: ModInfo };
};
