// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SupportedGame } from "./SupportedGame";

export type ModVersion = {
  version: string;
  publishedDate: string;
  assets: { [key in string]?: string | null };
  supportedGames: Array<SupportedGame> | null;
};
