// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModInfo } from "./ModInfo";

export type AvailableModsByGame = { jak1: Array<ModInfo>, jak2: Array<ModInfo>, jak3: Array<ModInfo>, };
